### ISSUE TITLE
Elatec.NET package Issue

### ISSUE THREAD

**Issue by mahdishojaei** [c3rebro/Elatec.NET#1]
Hi, 

Thank you for your useful repositories and projects.

I used to build your code Elatec.NET as a class library, but you used 2 libraries named "Log4CSharp" and "ByteArrayHelper.Extensions".
 
Firstly there are no Log4CSharp class libraries or NuGet packages are exist in the code or your repositories. 

Secondly ByteArrayHelper you used in Elatec.Net are different from your ByteArrayHelper repositories for example some function like SearchBytePattern or Trim do not exist in your ByteArrayHelper repositories.

could you please help us to fix this issue, especially about ByteArrayHelper repositories who does not compatible with Elatec.NET? 

Best Regard

**Comment by c3rebro** [comment]
Hi, and sorry. To be honest, i did not expect someone to make any use of these. But I'll try to fix it this weekend by integrating the nessesary classes which do not really needed to be seperated projects. I come back for you when i finished this.

Freundlich grüßt

Steven

Diese Nachricht habe ich von Unterwegs für Sie verfasst.

________________________________
Von: mahdishojaei ***@***.***>
Gesendet: Samstag, 4. November 2023 14:10
An: c3rebro/Elatec.NET
Cc: Subscribed
Betreff: [c3rebro/Elatec.NET] Elatec.NET package Issue (Issue #1) 

Hi,
Thank you for your useful repositories and projects.
I used to build your code Elatec.NET as a class library, but you used 2 libraries named "Log4CSharp" and "ByteArrayHelper.Extensions".
Firstly there are no Log4CSharp class libraries or NuGet packages are exist in the code or your repositories.
Secondly ByteArrayHelper you used in Elatec.Net are different from your ByteArrayHelper repositories for example some function like SearchBytePattern or Trim do not exist in your ByteArrayHelper repositories.
could you please help us to fix this issue, especially about ByteArrayHelper repositories who does not compatible with Elatec.NET?
Best Regard

**Comment by c3rebro** [comment]
Done. I do integrated the necessary Classes into the Project.

**Comment by mahdishojaei** [comment]
Great, thank you for so quick Modification, could please share your Usage sample project for use this class library?

**Comment by c3rebro** [comment]
I uploaded a Sample. You could make use of this one: 

https://github.com/c3rebro/Elatec.Net.SampleApp
